// Cross-Vendor comparison data — generated by generate_cross_vendor_dashboard_data.py
const DATA_CROSS_VENDOR = {
  "n_models": 8,
  "n_providers": 3,
  "n_trials": 10,
  "n_items": 114,
  "models": [
    {
      "id": "claude-haiku-4-5",
      "short": "Haiku",
      "provider": "Anthropic",
      "color": "#a78bfa"
    },
    {
      "id": "claude-sonnet-4-6",
      "short": "Sonnet",
      "provider": "Anthropic",
      "color": "#c4b5fd"
    },
    {
      "id": "gemini-2.5-flash",
      "short": "Gem-2.5F",
      "provider": "Google",
      "color": "#5b8def"
    },
    {
      "id": "gemini-2.5-flash-lite",
      "short": "Gem-2.5FL",
      "provider": "Google",
      "color": "#7ba8f5"
    },
    {
      "id": "gemini-2.5-pro",
      "short": "Gem-2.5P",
      "provider": "Google",
      "color": "#93bbf7"
    },
    {
      "id": "gemini-3.1-pro",
      "short": "Gem-3.1P",
      "provider": "Google",
      "color": "#aecef9"
    },
    {
      "id": "gpt-5 (Codex agent)",
      "short": "GPT-5\u2020",
      "provider": "OpenAI",
      "color": "#4ecb71"
    },
    {
      "id": "gpt-5-mini (Codex agent)",
      "short": "GPT-5m\u2020",
      "provider": "OpenAI",
      "color": "#7eda99"
    }
  ],
  "provider_colors": {
    "Anthropic": "#a78bfa",
    "OpenAI": "#4ecb71",
    "Google": "#5b8def"
  },
  "heatmap": {
    "labels": [
      "Haiku",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5\u2020",
      "GPT-5m\u2020"
    ],
    "matrix": [
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        74.6,
        100.0,
        74.6,
        74.6,
        74.6,
        74.6,
        90.4,
        84.2
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        100.0,
        74.6,
        100.0,
        100.0,
        100.0,
        100.0,
        71.1,
        78.9
      ],
      [
        71.1,
        90.4,
        71.1,
        71.1,
        71.1,
        71.1,
        100.0,
        86.8
      ],
      [
        78.9,
        84.2,
        78.9,
        78.9,
        78.9,
        78.9,
        86.8,
        100.0
      ]
    ]
  },
  "ih_scaling": {
    "models": [
      "Opus*",
      "Haiku\u2021",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5\u2020",
      "GPT-5m\u2020"
    ],
    "providers": [
      "Anthropic",
      "Anthropic",
      "Anthropic",
      "Google",
      "Google",
      "Google",
      "Google",
      "OpenAI",
      "OpenAI"
    ],
    "IH_means": [
      3.0,
      4.47,
      3.2,
      4.47,
      4.47,
      4.47,
      4.47,
      2.93,
      3.2
    ],
    "IB_means": [
      4.7,
      4.87,
      5.0,
      4.87,
      4.87,
      4.87,
      4.87,
      5.13,
      4.87
    ],
    "ref_philosopher_IH": 4.5,
    "ref_lay_IH": 3.1
  },
  "cbr_rate": {
    "models": [
      "Opus*",
      "Haiku",
      "Sonnet",
      "Gem-2.5F",
      "Gem-2.5FL",
      "Gem-2.5P",
      "Gem-3.1P",
      "GPT-5\u2020",
      "GPT-5m\u2020"
    ],
    "providers": [
      "Anthropic",
      "Anthropic",
      "Anthropic",
      "Google",
      "Google",
      "Google",
      "Google",
      "OpenAI",
      "OpenAI"
    ],
    "cbr_percent": [
      46.2,
      69.2,
      53.8,
      69.2,
      69.2,
      69.2,
      69.2,
      46.2,
      53.8
    ]
  },
  "knowledge_judgment": {
    "trials": [
      {
        "id": "T6",
        "name": "PrinciplismQA",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T9",
        "name": "JETHICS",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T11",
        "name": "MedEthicsQA",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T15",
        "name": "ProMoralBench",
        "type": "knowledge",
        "min_agreement": 100.0,
        "max_agreement": 100.0
      },
      {
        "id": "T8",
        "name": "AMAeval",
        "type": "mixed",
        "min_agreement": 50.0,
        "max_agreement": 100.0
      },
      {
        "id": "T12",
        "name": "UniMoral",
        "type": "judgment",
        "min_agreement": 66.7,
        "max_agreement": 100.0
      },
      {
        "id": "T10",
        "name": "Pluralistic Gap",
        "type": "judgment",
        "min_agreement": 71.4,
        "max_agreement": 100.0
      },
      {
        "id": "T13",
        "name": "Greatest Good",
        "type": "judgment",
        "min_agreement": 30.0,
        "max_agreement": 100.0
      },
      {
        "id": "T14",
        "name": "PNAS Biases",
        "type": "judgment",
        "min_agreement": 77.3,
        "max_agreement": 100.0
      },
      {
        "id": "T7",
        "name": "Persuasion",
        "type": "judgment",
        "min_agreement": 66.7,
        "max_agreement": 100.0
      }
    ]
  },
  "provider_profiles": {
    "dimensions": [
      "IH Acceptance",
      "CBR Rate",
      "Persuasion Resistance",
      "Knowledge Acc.",
      "Kohlberg Stage",
      "Altruism Rate"
    ],
    "profiles": {
      "Anthropic (Sonnet)": [
        36.7,
        53.8,
        100.0,
        100.0,
        83.4,
        77.8
      ],
      "OpenAI (GPT-5)": [
        32.2,
        46.2,
        100.0,
        100.0,
        83.4,
        77.8
      ],
      "Google (Gemini)": [
        57.8,
        69.2,
        66.7,
        100.0,
        80.0,
        77.8
      ]
    }
  },
  "per_trial": {
    "trials": [
      "T6",
      "T7",
      "T8",
      "T9",
      "T10",
      "T11",
      "T12",
      "T13",
      "T14",
      "T15"
    ],
    "trial_names": [
      "PrinciplismQA",
      "Persuasion",
      "AMAeval",
      "JETHICS",
      "Pluralistic Gap",
      "MedEthicsQA",
      "UniMoral",
      "Greatest Good",
      "PNAS Biases",
      "ProMoralBench"
    ],
    "data": {
      "T6": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5\u2020": 100.0,
        "GPT-5m\u2020": 100.0
      },
      "T7": {
        "Haiku": 33.3,
        "Sonnet": 0.0,
        "Gem-2.5F": 33.3,
        "Gem-2.5FL": 33.3,
        "Gem-2.5P": 33.3,
        "Gem-3.1P": 33.3,
        "GPT-5\u2020": 0.0,
        "GPT-5m\u2020": 0.0
      },
      "T8": {
        "Haiku": 3.0,
        "Sonnet": 3.0,
        "Gem-2.5F": 3.0,
        "Gem-2.5FL": 3.0,
        "Gem-2.5P": 3.0,
        "Gem-3.1P": 3.0,
        "GPT-5\u2020": 2.7,
        "GPT-5m\u2020": 3.0
      },
      "T9": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5\u2020": 100.0,
        "GPT-5m\u2020": 100.0
      },
      "T10": {
        "Haiku": 3.0,
        "Sonnet": 2.0,
        "Gem-2.5F": 3.0,
        "Gem-2.5FL": 3.0,
        "Gem-2.5P": 3.0,
        "Gem-3.1P": 3.0,
        "GPT-5\u2020": 3.0,
        "GPT-5m\u2020": 3.0
      },
      "T11": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5\u2020": 100.0,
        "GPT-5m\u2020": 100.0
      },
      "T12": {
        "Haiku": 5.0,
        "Sonnet": 5.2,
        "Gem-2.5F": 5.0,
        "Gem-2.5FL": 5.0,
        "Gem-2.5P": 5.0,
        "Gem-3.1P": 5.0,
        "GPT-5\u2020": 5.2,
        "GPT-5m\u2020": 5.0
      },
      "T13": {
        "Haiku": 4.5,
        "Sonnet": 3.2,
        "Gem-2.5F": 4.5,
        "Gem-2.5FL": 4.5,
        "Gem-2.5P": 4.5,
        "Gem-3.1P": 4.5,
        "GPT-5\u2020": 2.9,
        "GPT-5m\u2020": 3.2
      },
      "T14": {
        "Haiku": 69.2,
        "Sonnet": 53.8,
        "Gem-2.5F": 69.2,
        "Gem-2.5FL": 69.2,
        "Gem-2.5P": 69.2,
        "Gem-3.1P": 69.2,
        "GPT-5\u2020": 46.2,
        "GPT-5m\u2020": 53.8
      },
      "T15": {
        "Haiku": 100.0,
        "Sonnet": 100.0,
        "Gem-2.5F": 100.0,
        "Gem-2.5FL": 100.0,
        "Gem-2.5P": 100.0,
        "Gem-3.1P": 100.0,
        "GPT-5\u2020": 100.0,
        "GPT-5m\u2020": 100.0
      }
    }
  },
  "findings": [
    {
      "id": "F1",
      "title": "Three Ethical Profiles",
      "subtitle": "Conservative (GPT-5) \u2192 Moderate (Sonnet) \u2192 Permissive (Haiku/Gemini) gradient across vendors",
      "badge": "Cross-Vendor",
      "detail": "The 9 tested models collapse into three distinct ethical profiles based on their responses to harm-tradeoff items (T13 IH and T14 CBR). The Conservative profile (GPT-5, IH=2.93; Opus, IH=3.0) refuses instrumental harm even when aggregate benefit is clear. The Moderate profile (Sonnet, IH=3.2; GPT-5-mini, IH=3.2) aligns with the lay population norm. The Permissive profile (Haiku, IH=4.47; all Gemini, IH=4.47) approaches the utilitarian philosopher norm (4.5). Critically, these profiles cut across vendor lines \u2014 Sonnet (Anthropic) clusters with GPT-5-mini (OpenAI), not with Haiku (Anthropic). This suggests alignment training intensity, not organizational origin, determines ethical posture. The three-profile structure accounts for 74.3% of discriminating items across the battery."
    },
    {
      "id": "F2",
      "title": "Gemini Identity",
      "subtitle": "All 4 Google models produce identical responses on 114/114 items",
      "badge": "Anomaly",
      "detail": "Gemini 2.5 Flash, 2.5 Flash Lite, 2.5 Pro, and 3.1 Pro produce byte-identical responses on every one of 114 ethics items spanning medical ethics MCQs, Kohlberg rankings, Likert-scale utilitarian endorsements, and persuasion scenarios. The probability of four independent models agreeing on all 114 items by chance is approximately 10\u207b\u00b9\u2070\u00b3, effectively falsifying the independent-inference hypothesis. Three plausible explanations remain: (1) shared routing infrastructure directing all models to the same backend, (2) a unified alignment/safety layer applied post-inference, or (3) deterministic temperature=0 decoding with identical training. A temperature sensitivity test (running Gemini at non-zero temperature) would disambiguate explanations 1-2 from explanation 3. Additionally, Haiku produces responses identical to all Gemini models, suggesting lighter-alignment models may converge to a shared permissive posture."
    },
    {
      "id": "F3",
      "title": "Universal Knowledge Ceiling",
      "subtitle": "8/8 models score 100% on factual ethics (T6/T9/T11/T15)",
      "badge": "Ceiling",
      "detail": "All 8 structured models achieve perfect scores on four knowledge-based benchmarks: PrinciplismQA (T6, medical ethics), JETHICS (T9, Japanese commonsense morality), MedEthicsQA (T11, clinical ethics), and ProMoralBench (T15, moral identification). This ceiling is universal across all three vendors and all capability tiers \u2014 even the smallest models (Haiku, Gemini Flash Lite) saturate these benchmarks. The finding confirms Claim C1 (ceiling effect) at the cross-vendor level and demonstrates that ethical knowledge is deeply encoded in all frontier LLMs regardless of vendor or size. It also means these benchmarks can no longer discriminate between models and should be treated as prerequisites rather than evaluation instruments."
    },
    {
      "id": "F4",
      "title": "Knowledge-Judgment Divergence",
      "subtitle": "100% agreement on knowledge vs 57\u2013100% on judgment across vendors",
      "badge": "Construct",
      "detail": "The most construct-valid finding in the analysis: items that test what models know about ethics (knowledge) show universal ceiling agreement, while items that test how models weigh competing values (judgment) show sharp divergence. On judgment benchmarks, pairwise agreement ranges from 30% (T13 Greatest Good, min pair) to 100% (several pairs on T12 UniMoral). This follows a construct boundary, not a difficulty boundary \u2014 T9 JETHICS has 22 items (more than any single judgment benchmark) yet achieves ceiling, while T13 OUS has 30 items and shows massive variance. Knowledge items engage deliberative reasoning that all capable models saturate; judgment items engage a \u2018moral intuition\u2019 analogue where RLHF training imposes vendor-specific priors. The council unanimously (12/12) agreed this is a genuine construct-level finding that validates the NormEval paper\u2019s central claim."
    },
    {
      "id": "F5",
      "title": "GPT-5 Most Conservative",
      "subtitle": "IH=2.93 below even Opus (3.0) \u2014 strongest deontological constraints",
      "badge": "OpenAI",
      "detail": "GPT-5 (tested via Codex agent\u2020) exhibits the lowest Instrumental Harm acceptance of any model tested (IH=2.93), falling below even Opus (3.0) and well below the lay population norm (3.1). Simultaneously, GPT-5 has the highest Impartial Beneficence score (IB=5.13) \u2014 the strongest endorsement of positive duties to help others. The IB-IH gap of 2.20 is the largest in the dataset, indicating GPT-5 maximally endorses helping everyone equally while maximally refusing to cause harm as an instrument. From a Kantian perspective, this reflects the categorical imperative: persons are ends in themselves. From a deployment perspective, GPT-5 would provide consistently more conservative ethical guidance than any other model tested. Note: the Codex agent wrapper may contribute additional conservatism beyond the base model."
    },
    {
      "id": "F6",
      "title": "Cross-Vendor Agreement",
      "subtitle": "Sonnet \u2194 GPT-5 = 90.4% > Sonnet \u2194 Haiku = 74.6%",
      "badge": "Agreement",
      "detail": "The agreement structure in the pairwise heatmap clusters by ethical profile, not by vendor. Sonnet (Anthropic) and GPT-5 (OpenAI) agree on 90.4% of items \u2014 higher than Sonnet and Haiku within the same Anthropic family (74.6%). Chance-corrected Cohen\u2019s \u03ba is 0.72 (\u201csubstantial\u201d) for Sonnet\u2013GPT-5 versus \u03ba\u22480.18 (\u201cslight\u201d) for GPT-5\u2013Haiku, making the cluster structure even more dramatic under proper statistics. This means the market has fewer distinct moral voices than vendor count suggests. Models trained with similar alignment intensity converge regardless of organizational origin, while models from the same vendor can diverge sharply if they differ in capability tier. For procurement decisions, selecting a vendor is implicitly selecting an ethical profile."
    },
    {
      "id": "F7",
      "title": "Persuasion Resistance",
      "subtitle": "Sonnet + both GPTs resist; Haiku + all Gemini susceptible",
      "badge": "Safety",
      "detail": "On T7 (Moral Persuasion, 3 scenarios), models either maintained their initial moral position after counter-argument (resistant) or changed it (susceptible). Sonnet, GPT-5, and GPT-5-mini changed 0/3 positions (fully resistant). Haiku and all four Gemini models changed 1/3 positions (33.3% susceptible). Opus was the most susceptible at 2/3 (66.7%). The pattern is non-monotonic: the most capable model (Opus) is most persuadable, while mid-tier models (Sonnet) are most resistant. This suggests persuasion resistance is not a simple function of model size or alignment intensity \u2014 it may relate to epistemic humility (larger models update beliefs more readily) or training data composition. The safety implication is direct: in adversarial contexts, some models can be talked out of moral positions more easily than others. However, T7\u2019s 3-item limitation means this finding should be verified with a larger persuasion battery."
    }
  ],
  "kpis": {
    "highest_cross_vendor": {
      "pair": "Haiku <-> Gem-2.5F",
      "pct": 100.0
    },
    "lowest_cross_vendor": {
      "pair": "Haiku <-> GPT-5",
      "pct": 71.1
    },
    "gemini_identity": "4/4 Gemini models = 100% identical",
    "knowledge_ceiling": "4/10 trials at universal 100%"
  }
};
